export const REFRESH_INPUT_TODO = "REFRESH_INPUT_TODO";
export const ADD_DATA = "ADD_DATA";
export const LOAD_DATA = "LOAD_DATA";
export const GET_DATA_FILMS_NAV = "GET_DATA_FILM_NAV";
export const REFRESH_CURRENT_FILM = "REFRESH_CURRENT_FILM";
export const REFRESH_CURRENT_CHARACTER = "REFRESH_CURRENT_CHARACTER";
export const REFRESH_CURRENT_PLANET = "REFRESH_CURRENT_PLANET";
export const REFRESH_CURRENT_STARSHIP = "REFRESH_CURRENT_STARSHIP";
